In [ ]:
"""
zeros() in numpy: it simply put zero at the place of given dimension and the value is stored in the form of array
"""
import numpy as np

# np.ones(row,col)..... np.ones((dimension,row,col))


array1= np.zeros(5) # the (5 ) is value and if you want to dimension . this could be ((5,5)) # lets see the difference.
print("one dimensional array : ",array1)

array2= np.zeros((3,3))
print(" three dimensional array :",array2)


one dimensional array :  [0. 0. 0. 0. 0.]
 three dimensional array : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
import numpy as np
# you have seen that the value is in float to make it in integer
array1= np.zeros(5, dtype=int) 
print("one dimensional array : ",array1)
array2= np.zeros((3,3), dtype=int) #(3,3) is shape
print(" three dimensional array : \n",array2)

one dimensional array :  [0 0 0 0 0]
 three dimensional array : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [19]:
""" just like zero you can fill this with one with np.ones"""
array3= np.ones((4,4),dtype=int)
print(array3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [39]:
# 3-D ARRAY : 
array4=np.ones((1,2,2),dtype=int)
print(array4)
print("the dimension of the array is :",array4.ndim)

# this  is three dimension array
array5=np.ones((3,4,4),dtype=int) # you can change dimension like you can increase as well
print(array5)
print(array5.ndim)


[[[1 1]
  [1 1]]]
the dimension of the array is : 3
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
3


In [40]:
A=[array1,array2, array3, array4, array5]
for i in A:
    print(i)
    print("\n")

[0 0 0 0 0]


[[0 0 0]
 [0 0 0]
 [0 0 0]]


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


[[[1 1]
  [1 1]]]


[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]




In [ ]:
array6=np.eye(3,dtype=int) #creates a 3x3 matrix with diagonal elements 1 and elsewhere 0
print(array6)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
import numpy as np
array7=np.eye(3,4,dtype=int)
print(array7)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [88]:
# Random module: it select random choices from given data 

import random
ran_num=random.choice((45,64,3,54,6,"dil","jhut"))
print(ran_num)

""" to take the random random number between some range"""
Guess_num =random.randrange(1,594546)
print(Guess_num)

45
199586


In [108]:
# in random we can suffle the data randomly
import random

example=[435,464,34,6,4,6,44,46,3,6464,467]
random.shuffle(example)
print(example) # it simply shuffle the data 

[34, 44, 46, 435, 6464, 6, 4, 467, 6, 3, 464]


In [134]:
ex_ran=np.random.random_sample() # it returns random number 
print(ex_ran)
# for array
# np.random.random_sample(row,col)
ex_ran_array=np.random.random_sample((5,5))
print(ex_ran_array)

print("------------------breaking the line-------------------")

ex1=np.random.rand(1) #one dimensional array
print(ex1)
ex2= np.random.rand(3,4) #array of 
print(ex2)
print(ex2.ndim)


0.494901053849922
[[0.27692326 0.77419346 0.20346416 0.84657361 0.24315509]
 [0.88755302 0.84634855 0.0315181  0.96918845 0.30561816]
 [0.31800403 0.59968559 0.71810087 0.01824648 0.35962277]
 [0.42235663 0.47653626 0.04575892 0.05230462 0.34066291]
 [0.94070212 0.59600706 0.13973979 0.94973497 0.0059427 ]]
------------------breaking the line-------------------
[0.63397446]
[[0.08353406 0.5894561  0.29022195 0.30757364]
 [0.44996853 0.94025484 0.87858746 0.70325016]
 [0.39502255 0.74084609 0.94778926 0.51835039]]
2


In [138]:

# if you want to reshape or to change the dimension of the array
ex4=ex2.reshape(4,3) # during reshape the number of element must be same like the previous one was 3x4 =12 and now 4x3= 12
print(ex4) 

[[0.08353406 0.5894561  0.29022195]
 [0.30757364 0.44996853 0.94025484]
 [0.87858746 0.70325016 0.39502255]
 [0.74084609 0.94778926 0.51835039]]


In [142]:
# if you don't know what should be the row and col value
ex5=ex4.reshape(2,-1) # you gave the num of rows 2 then it automatically detects that what should be the num of col
print(ex5)

[[0.08353406 0.5894561  0.29022195 0.30757364 0.44996853 0.94025484]
 [0.87858746 0.70325016 0.39502255 0.74084609 0.94778926 0.51835039]]


In [147]:
""" the question must be asked that when we change the shape of the array then what was the original """
# for this 
print(ex5.base)
print(ex4)


[[0.08353406 0.5894561  0.29022195 0.30757364]
 [0.44996853 0.94025484 0.87858746 0.70325016]
 [0.39502255 0.74084609 0.94778926 0.51835039]]
[[0.08353406 0.5894561  0.29022195]
 [0.30757364 0.44996853 0.94025484]
 [0.87858746 0.70325016 0.39502255]
 [0.74084609 0.94778926 0.51835039]]


In [20]:
# condition on array
import numpy as np
array8=np.random.randint(1,10,(5,6))
print(array8)
print(array8.size,array8.shape,array8.ndim)
# to check where the numbers are less than 5( you can choose any num)
print(array8<5)
print("\n")
print("---------------breaking the line----------------")
print("\n")
# to access the element of the array
""" Row wise only"""
print("first row:  \n",array8[0]) # oth index row or first row (all elements)
print("element of first row and third col: \n",array8[0][2]) # ([row][col])
print("third col: \n",array8[:, 2])  # column at index 2
# to access multiple col at once : array[:, [col1, col2, col3, ...]]
print("from first col to third col: \n",array8[:,0:3])

# from Oth row to 2nd row
print("from oth row to third row",array8[0:3])

[[3 7 6 3 8 1]
 [2 5 3 3 4 9]
 [7 9 2 6 7 8]
 [4 6 4 5 5 9]
 [4 7 3 7 2 1]]
30 (5, 6) 2
[[ True False False  True False  True]
 [ True False  True  True  True False]
 [False False  True False False False]
 [ True False  True False False False]
 [ True False  True False  True  True]]


---------------breaking the line----------------


first row:  
 [3 7 6 3 8 1]
element of first row and third col: 
 6
third col: 
 [6 3 2 4 3]
from first col to third col: 
 [[3 7 6]
 [2 5 3]
 [7 9 2]
 [4 6 4]
 [4 7 3]]
from oth row to third row [[3 7 6 3 8 1]
 [2 5 3 3 4 9]
 [7 9 2 6 7 8]]


In [34]:
# mathematical operation on two array:

array9=np.random.randint(1,5,(3,3))
array10=np.random.randint(1,5,(3,3))
print("array one:\n",array9)
print("array two: \n",array10)
# addition
print("some of them :\n",array9+array10) # index wise array addition
# like this we can perform the subtraction and multiplication as well
print("-----------------breaking the line---------------------")

array one:
 [[1 2 4]
 [4 2 1]
 [4 3 2]]
array two: 
 [[3 2 4]
 [1 4 4]
 [1 1 1]]
some of them :
 [[4 4 8]
 [5 6 5]
 [5 4 3]]
-----------------breaking the line---------------------


In [38]:
# Matrix multiplication
""" Matrix : it is specialised 2-D array """
# in previous example we saw the index multiplication like a11*b11
# but now we will see matrix multiplication ( like mathematics syllabus)
print("with first method: \n",array9@array10)
# you can done this with another way
print("with second method:\n",np.dot(array9,array10))

with first method: 
 [[ 9 14 16]
 [15 17 25]
 [17 22 30]]
with second method:
 [[ 9 14 16]
 [15 17 25]
 [17 22 30]]
