In [ ]:
"""
zeros() in numpy: it simply put zero at the place of given dimension and the value is stored in the form of array
"""
import numpy as np

# np.ones(row,col)..... np.ones((dimension,row,col))


array1= np.zeros(5) # the (5 ) is value and if you want to dimension . this could be ((5,5)) # lets see the difference.
print("one dimensional array : ",array1)

array2= np.zeros((3,3))
print(" three dimensional array :",array2)


one dimensional array :  [0. 0. 0. 0. 0.]
 three dimensional array : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
import numpy as np
# you have seen that the value is in float to make it in integer
array1= np.zeros(5, dtype=int) 
print("one dimensional array : ",array1)
array2= np.zeros((3,3), dtype=int) #(3,3) is shape
print(" three dimensional array : \n",array2)

one dimensional array :  [0 0 0 0 0]
 three dimensional array : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [19]:
""" just like zero you can fill this with one with np.ones"""
array3= np.ones((4,4),dtype=int)
print(array3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [39]:
# 3-D ARRAY : 
array4=np.ones((1,2,2),dtype=int)
print(array4)
print("the dimension of the array is :",array4.ndim)

# this  is three dimension array
array5=np.ones((3,4,4),dtype=int) # you can change dimension like you can increase as well
print(array5)
print(array5.ndim)


[[[1 1]
  [1 1]]]
the dimension of the array is : 3
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
3


In [40]:
A=[array1,array2, array3, array4, array5]
for i in A:
    print(i)
    print("\n")

[0 0 0 0 0]


[[0 0 0]
 [0 0 0]
 [0 0 0]]


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


[[[1 1]
  [1 1]]]


[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]




In [ ]:
array6=np.eye(3,dtype=int) #creates a 3x3 matrix with diagonal elements 1 and elsewhere 0
print(array6)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
import numpy as np
array7=np.eye(3,4,dtype=int)
print(array7)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [88]:
# Random module: it select random choices from given data 

import random
ran_num=random.choice((45,64,3,54,6,"dil","jhut"))
print(ran_num)

""" to take the random random number between some range"""
Guess_num =random.randrange(1,594546)
print(Guess_num)

45
199586
