In [ ]:
"""
zeros() in numpy: it simply put zero at the place of given dimension and the value is stored in the form of array
"""
import numpy as np
array1= np.zeros(5) # the (5 ) is value and if you want to dimension . this could be ((5,5)) # lets see the difference.
print("one dimensional array : ",array1)

array2= np.zeros((3,3))
print(" three dimensional array :",array2)


one dimensional array :  [0. 0. 0. 0. 0.]
 three dimensional array : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
import numpy as np
# you have seen that the value is in float to make it in integer
array1= np.zeros(5, dtype=int) 
print("one dimensional array : ",array1)
array2= np.zeros((3,3), dtype=int) #(3,3) is shape
print(" three dimensional array : \n",array2)

one dimensional array :  [0 0 0 0 0]
 three dimensional array : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
